### ISSUE TITLE
500 Internal Server Error on first load

### ISSUE THREAD

**Issue by nicholasngai** [monty5811/elvanto_mail_sync#7]
Hi! I’m trying to get this app to work, but I keep getting a 500 Internal Server Error whenever I try to pull up the web app, and Rollbar outputs me the following error:

```Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 96, in dispatch
    app = provider.get_app(self.request)
  File "/app/.heroku/python/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 52, in get_app
    return SocialApp.objects.get_current(self.id, request)
  File "/app/.heroku/python/lib/python3.6/site-packages/allauth/socialaccount/models.py", line 34, in get_current
    provider=provider)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
DoesNotExist: SocialApp matching query does not exist.```

Thanks! I’m wondering if I set up the Google service account or OAuth wrong… Could you provide more detailed instructions for that, as well?

**Comment by monty5811** [comment]
Have you deployed to heroku? Or somewhere else?

**Comment by nicholasngai** [comment]
Sorry for the late response. It’s deployed to Heroku using the Deploy to Heroku button.
